services:
  # Development environment
  frontend-dev:
    build:
      context: .
      target: development
    container_name: online-scheduling-frontend-dev
    ports:
      - "3003:3003"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    command: sh -c "npm install && npm run dev"
    stdin_open: true
    tty: true
    restart: unless-stopped