apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-dev
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3003
      nodePort: 30000